---
title: "Renyi - simulacija i animacija"
author: "Borna Odobašić, Istok Korkut, Lovro Matić"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r}
flory <- function(n, k, offset = 0) {
  #uvjet kraja rekurzije
  if (k > n) {
    return(numeric(0))  
  }
  
  #bira se jedan broj između dostupnih mjesta
  x <- sample(0:(n - k), 1) 
  pos <- offset + x
  
  left_positions <- flory(x, k, offset)
  right_positions <- flory(n - k - x, k, offset + x + k)
  
  c(pos, left_positions, right_positions)
}
```

```{r}
set.seed(12)

n <- 20
k <- 2

pozicije <- flory(n, k)
pozicije <- sort(pozicije)

dfCars <- data.frame(
  car = seq_along(pozicije),
  start = pozicije,
  end = pozicije + k - 1
)

df_ticks <- data.frame(
  x = 0:n
)

ggplot() + 
  geom_segment(aes(x = 0, xend = n, y = 1, yend = 1),
               size = 1.5, color = "black") +
  geom_segment(data = df_ticks,
               aes(x = x, xend = x, y = 0.9, yend = 1.1),
               color = "black", size = 1) +
  geom_rect(data = dfCars,
            aes(xmin = start, xmax = end, ymin = 0.8, ymax = 1.2, fill = factor(car)), color = "blue", alpha = 0.6) +
  geom_text(data = dfCars,
            aes(x = (start + end)/2, y = 1.4, label = car),
            size = 4) +
  scale_fill_discrete(guide = "none") +
  scale_x_continuous(limits = c(0, n)) +
  scale_y_continuous(limits = c(0.5, 2)) + 
  labs(x = "Pozicije", y = "", title = "Simulirani Floryjev model parkiranja")
```

